name: autofix.ci

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MSRV: "1.80"  # Minimum Supported Rust Version

jobs:
  protobuf:
    runs-on: macos-latest
    steps:
      - uses: mhils/workflows/checkout@v12
      - run: brew install swift-protobuf
      - run: cargo install protoc-gen-prost
      - run: protoc --proto_path=./src/ipc/ mitmproxy_ipc.proto
          --prost_out=./src/ipc/
          --swift_out=./mitmproxy-macos/redirector/ipc
      - run: cargo fmt --all
      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a

  rustfmt:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: macos-latest
          - os: ubuntu-latest
    steps:
      - uses: mhils/workflows/checkout@v12
      - uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ env.MSRV }}
          toolchain-args: --component rustfmt --component clippy

      - run: cargo clippy --fix --allow-dirty --workspace
      - run: cargo fmt --all
      - run: git checkout src/ipc/mitmproxy_ipc.rs

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
